- 'Phpeel\ApricotLib\Type\Int\Integer'
- 'Phpeel\ApricotLib\Type\Int\UnsignedInt'
- 'Phpeel\ApricotLib\Type\Float\Float'
- 'Phpeel\ApricotLib\Type\Float\UnsignedFloat'
- 'Phpeel\ApricotLib\Type\String\String'
- 'Phpeel\ApricotLib\Type\String\Text'
- 'Phpeel\ApricotLib\Caching\MemcacheAgent'
- 'Phpeel\ApricotLib\Caching\ApcAgent'
